# Generated by Django 4.2.7 on 2026-02-02 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(help_text='Uploaded CSV file', upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of upload')),
                ('total_equipment_count', models.IntegerField(default=0, help_text='Total number of equipment entries')),
                ('average_pressure', models.FloatField(default=0.0, help_text='Average pressure across all equipment (bar)')),
                ('average_temperature', models.FloatField(default=0.0, help_text='Average temperature across all equipment (°C)')),
                ('equipment_type_distribution', models.TextField(blank=True, help_text='Distribution of equipment types in JSON format')),
            ],
            options={
                'verbose_name': 'Equipment Upload',
                'verbose_name_plural': 'Equipment Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='Name/ID of the equipment', max_length=200)),
                ('equipment_type', models.CharField(help_text='Type/category of equipment', max_length=100)),
                ('flowrate', models.FloatField(help_text='Flowrate in L/min or specified units')),
                ('pressure', models.FloatField(help_text='Operating pressure in bar')),
                ('temperature', models.FloatField(help_text='Operating temperature in °C')),
                ('upload', models.ForeignKey(help_text='Reference to the parent upload batch', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='equipment_api.equipmentupload')),
            ],
            options={
                'verbose_name': 'Equipment Data',
                'verbose_name_plural': 'Equipment Data',
                'ordering': ['equipment_name'],
            },
        ),
    ]
